### ISSUE TITLE
Visual Studio 2017 doesn't support .NET Core SDK 2.2.2 or later

### ISSUE THREAD

**Issue by dresdedream** [aspnet/AspNetCore.Docs.fr-fr#214]
So when you build, you get an IIS error. You need to install .NET Core SDK 2.2.1 to use on Visual Studio 2017.

---
#### Détails du document

⚠ *Ne pas modifier cette section. Elle est requise pour docs.microsoft.com ➟ problème de liaison GitHub.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutoriel : Bien démarrer avec des pages Razor dans ASP.NET Core](https://docs.microsoft.com/fr-ca/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/AspNetCore.Docs.fr-fr/blob/live/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Recommander la fermeture. Voir le document:

Prérequis

Visual Studio 2017 version 15.9 ou ultérieure avec la charge de travail ASP.NET et développement web
**Kit SDK .NET Core 2.2 ou version ultérieure**

**Comment by Rick-Anderson** [comment]
Ceci est corrigé maintenant. Vous pouvez fermer le problème.
@ dresdedream merci de nous l'avoir signalé.

**Comment by CeciAc** [comment]
Bonjour @dresdedream 

Merci pour votre feedback. 

Votre contribution à nos articles est grandement appréciée. Nous vous encourageons donc à continuer d’envoyer vos commentaires à Microsoft. 

Cordialement, 
L’équipe Microsoft DOCS International
