### ISSUE TITLE
ASP.Net Core With .Net Framework version different than the referenced docs

### ISSUE THREAD

**Issue by Davilink** [aspnet/AspNetCore.Docs.fr-fr#215]
I took the screenshot in English, but the problem is on the french version also.

In https://docs.microsoft.com/fr-ca/aspnet/core/?view=aspnetcore-2.2#aspnet-core-targeting-net-framework
![image](https://user-images.githubusercontent.com/1498932/59806770-8b9b4e80-92c3-11e9-964b-b6de1f7f6177.png)

In https://docs.microsoft.com/fr-fr/dotnet/standard/net-standard#net-implementation-support
![image](https://user-images.githubusercontent.com/1498932/59806840-cf8e5380-92c3-11e9-97c1-63c68458c408.png)

---
#### Détails du document

⚠ *Ne pas modifier cette section. Elle est requise pour docs.microsoft.com ➟ problème de liaison GitHub.*

* ID: ad8c13e7-78e6-cf9a-e7cb-3215df5fd1c4
* Version Independent ID: a3c1d2a6-625a-3409-120d-8372230a8196
* Content: [Présentation d’ASP.NET Core](https://docs.microsoft.com/fr-ca/aspnet/core/?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/index.md](https://github.com/aspnet/AspNetCore.Docs.fr-fr/blob/live/aspnetcore/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
PR #215 fixes this.

**Comment by CeciAc** [comment]
Hello, @Davilink 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review PR https://github.com/aspnet/AspNetCore.Docs/pull/12957 . For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
