### ISSUE TITLE
SignInResult.IsNotAllowed n'est pas expliqué

### ISSUE THREAD

**Issue by Davilink** [aspnet/AspNetCore.Docs.fr-fr#226]
Après avoir regardé à gauche et à droite, je suis tombé sur SignInResult.IsNotAllowed, mais cette propriété n'est pas du tout expliqué. À quoi elle sert ? Quel est le but de cette propriété ? Après avoir recherché sur Internet, j'ai trouvé des forums qui en parlait, mais selon moi ça devrait faire parti de la documentation.

---
#### Détails du document

⚠ *Ne pas modifier cette section. Elle est requise pour docs.microsoft.com ➟ problème de liaison GitHub.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction à Identity sur ASP.NET Core](https://docs.microsoft.com/fr-ca/aspnet/core/security/authentication/identity?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/AspNetCore.Docs.fr-fr/blob/live/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @Davilink
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
After looking left and right, I came across `SignInResult.IsNotAllowed`, but this property is not explained at all. What is it for? What is the purpose of this property? After looking on the Internet, I found forums that talked about it, but in my opinion it should be part of the documentation.

Returns a flag indicating whether the user attempting to sign-in is not allowed to sign-in.


Renvoie un drapeau indiquant si l'utilisateur qui tente de se connecter n'est pas autorisé à se connecter.

Recommend you close this issue.

**Comment by Davilink** [comment]
Should this concept be explain more in depth or has some example to how to use it and which condition it would be better to have a `NotAllowed` at true vs a `Success` at false ?

**Comment by Rick-Anderson** [comment]
It's only rarely needed. Those who need it figure out how to use it.

**Comment by Davilink** [comment]
I will close this issue for now.
