### ISSUE TITLE
Mauvaise traduction

### ISSUE THREAD

**Issue by SudHeb** [aspnet/AspNetCore.Docs.fr-fr#228]
Dans la version française de la doc, laissez Blazor.
La traduction automatique de la doc transforme 'Blazor' en 'éblouissant (e)' which mean 'sparckling'

---
#### Détails du document

⚠ *Ne pas modifier cette section. Elle est requise pour docs.microsoft.com ➟ problème de liaison GitHub.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Prise en main d’ASP.NET Core éblouissante](https://docs.microsoft.com/fr-ca/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio&utm_source=jeliknes&utm_medium=blog&utm_campaign=link&WT.mc_id=link-blog-jeliknes#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs.fr-fr/blob/live/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @SudHeb
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Bonjour @SudHeb 

Merci pour votre feedback. La page en question a été traduite automatiquement, ce qui ne permet pas toujours une bonne compréhension. Nous avons récemment ajouté l’option « Lire en anglais » (sur la droite) qui permet de lire la version anglaise sans avoir à modifier les paramètres de langue. 

Cordialement, 

L’équipe Microsoft DOCS International

--

@JasonCard MT translates product name
