### ISSUE TITLE
Doublons de phrase

### ISSUE THREAD

**Issue by Duff013** [aspnet/AspNetCore.Docs.fr-fr#229]
"Une alternative à l’injection de IHostingEnvironment consiste à utiliser une approche basée sur les conventions." apparait en double.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 793395fe-c738-22ce-d0e9-29a850c0fa88
* Version Independent ID: 0546ce3a-3258-9817-0f3f-13281c2f55da
* Content: [Démarrage d’une application dans ASP.NET Core](https://docs.microsoft.com/fr-fr/aspnet/core/fundamentals/startup?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/startup.md](https://github.com/aspnet/AspNetCore.Docs.fr-fr/blob/live/aspnetcore/fundamentals/startup.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @Duff013
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Bonjour, @Duff013
Nous vous remercions sincèrement pour votre commentaire et nous nous efforçons d’améliorer votre expérience dans docs.microsoft.com. Cependant, nous avons besoin de plus d’informations pour pouvoir répondre à vos commentaires. Pouvez-vous fournir des informations plus détaillées et clarifier votre commentaire ?

les deux phrases sont différentes
![imagen](https://user-images.githubusercontent.com/26746247/64268938-63f57300-cf0f-11e9-9b74-1f2a95a99a57.png)

Cordialement,
L’équipe internationale Microsoft DOCS

**Comment by CeciAc** [comment]
Bonjour @Duff013 

Merci pour votre feedback. 

Notre équipe linguistique a examiné vos suggestions de traduction et les a acceptées. Nous avons modifié les articles concernés selon vos suggestions et les avons republiés sur les pages https://docs.microsoft.com/fr-fr/aspnet/core/fundamentals/startup?view=aspnetcore-2.2 du site Docs.  

Votre contribution à nos articles est grandement appréciée. Nous vous encourageons donc à continuer d’envoyer vos commentaires à Microsoft. 

Cordialement, 
L’équipe Microsoft DOCS International
