### ISSUE TITLE
API and JSON code sample mismatch

### ISSUE THREAD

**Issue by cseguenot** [aspnet/AspNetCore.Docs.fr-fr#234]
Hi
There is an problem with the JSON code sample : it's about wheather forecast, and not about todo items...

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutoriel : Créer une API web avec ASP.NET Core](https://docs.microsoft.com/fr-fr/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs.fr-fr/blob/live/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @cseguenot
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [aspnet/AspNetCore #14797](https://github.com/aspnet/AspNetCore/issues/14797) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @cseguenot

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/aspnet/AspNetCore/issues/14797

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
> There is an problem with the JSON code sample : it's about wheather forecast, and not about todo items...

It's correct

![image](https://user-images.githubusercontent.com/3605364/66338296-90205d00-e8dc-11e9-9109-c8f65d992f47.png)

You must have selected the 2.2 version

![image](https://user-images.githubusercontent.com/3605364/66338341-a0383c80-e8dc-11e9-9a8e-29927af4b1e1.png)
