### ISSUE TITLE
SwaggerDoc extension method requires a Swashbuckle.AspNetCore.Swagger.Info parameter

### ISSUE THREAD

**Issue by DudePascalou** [aspnet/AspNetCore.Docs.fr-fr#236]
Before version 5.0.0 (which is not yet released, on november 2019), SwaggerDoc extension method requires a Swashbuckle.AspNetCore.Swagger.Info parameter. So, on "Add and configure Swagger middleware" section, you have to write :
```
    // Register the Swagger generator, defining 1 or more Swagger documents
    services.AddSwaggerGen(c =&gt;
    {
        c.SwaggerDoc("v1", new Info { Title = "My API", Version = "v1" });
    });
```
Beginning with version 5.0.0, SwaggerDoc extension method now requires a Microsoft.OpenApi.Models.OpenApiInfo parameter.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Bien démarrer avec Swashbuckle et ASP.NET Core](https://docs.microsoft.com/fr-fr/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/AspNetCore.Docs.fr-fr/blob/live/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by srvbpigh** [comment]
Hello, @DudePascalou
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [aspnet/AspNetCore #17309](https://github.com/aspnet/AspNetCore/issues/17309) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @DudePascalou

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/aspnet/AspNetCore/issues/17309

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
