### ISSUE TITLE
Example for CreateAuthenticatedChannel contains wrong information

### ISSUE THREAD

**Issue by christopheblin** [aspnet/AspNetCore.Docs.fr-fr#237]
In the doc, there is:
// SslCredentials is used here because this channel is using TLS.
// Channels that aren't using TLS should use ChannelCredentials.Insecure instead.

As I investigated in https://stackoverflow.com/a/58990584/1545567, ChannelCredentials.Insecure is not allowed to be combiend with CallCredentials

So the comment should be

//SslCredentials is required here, GRPC standard does not allow to send CallCredentials over insecured channel

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 363b40bb-4e20-e4b3-4456-5eb8fe6b30fb
* Version Independent ID: 8a7e85b0-5c1c-969d-9748-5e5e2dc45cce
* Content: [Authentification et autorisation dans gRPC pour ASP.NET Core](https://docs.microsoft.com/fr-fr/aspnet/core/grpc/authn-and-authz?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/grpc/authn-and-authz.md](https://github.com/aspnet/AspNetCore.Docs.fr-fr/blob/live/aspnetcore/grpc/authn-and-authz.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by christopheblin** [comment]
Note that this is not fr-fr specifically

**Comment by srvbpigh** [comment]
Hello, @christopheblin
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [aspnet/AspNetCore.Docs #15831](https://github.com/aspnet/AspNetCore.Docs/issues/15831) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @christopheblin 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/aspnet/AspNetCore.Docs/issues/15831

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
