### ISSUE TITLE
Suite et correctif du message d'hier..

### ISSUE THREAD

**Issue by Alama32** [aspnet/AspNetCore.Docs.fr-fr#240]
Aujourd'hui, j'ai toujours des erreurs, mais le programme a compilé quand même et semble fonctionner correctement.

les erreurs:
_____________________________________________________
Gravité	Code	Description	Projet	Fichier	Ligne	État de la suppression
Erreur	CS1061	'TodoItem' ne contient pas de définition pour 'IsDone' et aucune méthode d'extension accessible 'IsDone' acceptant un premier argument de type 'TodoItem' n'a été trouvée (une directive using ou une référence d'assembly est-elle manquante ?)	BlazorApp1	C:\Users\alama\source\repos\BlazorApp1\Pages\Todo.razor	9	Actif
Erreur	CS1061	'TodoItem' ne contient pas de définition pour 'IsDone' et aucune méthode d'extension accessible 'IsDone' acceptant un premier argument de type 'TodoItem' n'a été trouvée (une directive using ou une référence d'assembly est-elle manquante ?)	BlazorApp1	C:\Users\alama\source\repos\BlazorApp1\obj\Debug\netcoreapp3.1\Razor\Pages\Todo.razor.g.cs	119	Actif
Erreur	CS1061	'TodoItem' ne contient pas de définition pour 'IsDone' et aucune méthode d'extension accessible 'IsDone' acceptant un premier argument de type 'TodoItem' n'a été trouvée (une directive using ou une référence d'assembly est-elle manquante ?)	BlazorApp1	C:\Users\alama\source\repos\BlazorApp1\obj\Debug\netcoreapp3.1\Razor\Pages\Todo.razor.g.cs	119	Actif
Erreur	CS1061	'TodoItem' ne contient pas de définition pour 'IsDone' et aucune méthode d'extension accessible 'IsDone' acceptant un premier argument de type 'TodoItem' n'a été trouvée (une directive using ou une référence d'assembly est-elle manquante ?)	BlazorApp1	C:\Users\alama\source\repos\BlazorApp1\Pages\Todo.razor	1	Actif
Erreur	CS1061	'TodoItem' ne contient pas de définition pour 'IsDone' et aucune méthode d'extension accessible 'IsDone' acceptant un premier argument de type 'TodoItem' n'a été trouvée (une directive using ou une référence d'assembly est-elle manquante ?)	BlazorApp1	C:\Users\alama\source\repos\BlazorApp1\Pages\Todo.razor	1	Actif
Erreur	CS1061	'TodoItem' ne contient pas de définition pour 'IsDone' et aucune méthode d'extension accessible 'IsDone' acceptant un premier argument de type 'TodoItem' n'a été trouvée (une directive using ou une référence d'assembly est-elle manquante ?)	BlazorApp1	C:\Users\alama\source\repos\BlazorApp1\Pages\Todo.razor	3	Actif
_____________________________________________________

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Prise en main de ASP.NET Core Blazor](https://docs.microsoft.com/fr-fr/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs.fr-fr/blob/live/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @Alama32
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Bonjour @Alama32,  

Merci pour votre contribution. Votre feedback porte sur la documentation en langue anglaise.  

Nous l’avons donc transféré au dépôt Anglais. Vous pouvez consulter le statut de votre demande ici : https://github.com/aspnet/AspNetCore.Docs/issues/16665.  

Votre contribution à nos articles est grandement appréciée.   

Cordialement,  
L’équipe Microsoft DOCS International

**Comment by Alama32** [comment]
Hello,  sorry for that, is there the same documentation wth tutorials in French?
